version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: runner
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: webserver
    volumes:
      - ./docker/nginx:/etc/nginx
    ports:
      - '127.0.0.1:3000:80'